### ISSUE TITLE
Is the cronjob docker image working?

### ISSUE THREAD

**Issue by robrechtme** [KROSF/vercel-ddns#1]
Hi! I tried spinning up the `cronjob` Docker image on my raspberry pi, but it crashed with the following error

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

Do you have any idea what this means? 🙂

**Comment by KROSF** [comment]
sorry to tell you but this project is not compatible with armv6 or armv7.

if you are interested i can create a image for both versions

**Comment by robrechtme** [comment]
Thanks for your quick response! 
I eventually went with [iam-medvedev/vercel-ddns](https://github.com/iam-medvedev/vercel-ddns), which is just a bash script that needs to be configured in crontab. It's not as nice as a docker container, like this repo, but it suits my needs. No need to create those images just for me, but I really appreciate the work!
